services:
  # db:
  #   container_name: db
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  backend:
    container_name: backend-the-social-network
    build:
      context: ./backend
      dockerfile: Dockerfile
      # args:
      #   DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    network_mode: "host"

  frontend:
    container_name: frontend-the-social-network
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
        # Replace $IP with your ip address
      - DISPLAY=$IP:0
    network_mode: "host"
