services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    network_mode: "host"


  backend:
    depends_on:
      - db
    container_name: backend-the-social-network
    build:
      context: ./on1giri_server
      dockerfile: Dockerfile
    volumes:
      - $HOME/projects/rust/the_social_network/on1giri_server:/app
    ports:
      - "8000:8000"
    network_mode: "host"


  frontend:
    build:
      context: ./on1giri_client/frontend
      dockerfile: Dockerfile
    environment:
        # Replace $IP with your ip address on mac
        # Replace it with $DISPLAY on linux
      - DISPLAY=$DISPLAY:0
    volumes:
      - $HOME/projects/rust/the_social_network/on1giri_client/frontend:/app
    network_mode: "host"


volumes:
    db-data:
